pagarme/former-kit

- package.json
- src/Card/README.md
- stories/Card/CardExamples.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
Remove class sectionContent from theme shape on propTypes validations.
related with pagarme/former-kit-skin-pagarme#23
> chore: add CardContent to CardSection

- src/Button/index.md
- src/DateInput/index.js
- src/DateSelector/index.js
> fix some docs grammar

- src/Pagination/Pagination.test.js
- src/Pagination/index.js
- stories/Pagination/index.js
- stories/__snapshots__/storyshots.test.js.snap
> pagination: add disabled prop

- src/Pagination/index.js
- stories/__snapshots__/storyshots.test.js.snap
Depends on pagarme/former-kit-skin-pagarme#28
Closes #40
> pagination: add not-allowed cursor

- src/Table/TableExpandedRow.js
- src/Table/TableRow.js
- src/Table/tests/Table.static.test.js
- src/Table/tests/common.js
- stories/Table/TableState.js
- stories/Table/index.js
- stories/__snapshots__/storyshots.test.js.snap
Add a rule to render a empty item when a renderer return a falsy value
Closes #48
> Add empty renderer rule

- src/DateSelector/DateSelector.test.js
- src/DateSelector/index.js
- stories/__snapshots__/storyshots.test.js.snap
> date-selector: add anyDate preset

- src/Button/index.js
- Button children can receive a string or array of string.
> button: fix children prop validations

- src/Grid/Grid.js
- src/Landing/Landing.js
- stories/__snapshots__/storyshots.test.js.snap
This prop fix the full height bug on firefox.
> landing: add full-height prop

- src/Grid/Grid.js
- src/Table/README.md
- src/Table/TableExpandedRow.js
- src/Table/TableHead.js
- src/Table/TableRow.js
- src/Table/index.js
- stories/Table/TableState.js
- stories/Table/index.js
- stories/Table/tableMock.js
- stories/__snapshots__/storyshots.test.js.snap
Closes #44
Depends on https://github.com/pagarme/former-kit-skin-pagarme/pull/33
> table: add disabled state to table

- src/Grid/Col.js
- stories/Grid/CardSample.style.css
- stories/__snapshots__/storyshots.test.js.snap
the col alignment should allow both center, left and right alignments
the theme should also be changed for supporting that!
> grid-alignment: add new options to align

- CONTRIBUTING.md
This refactors the checklist to add a more clear storyshots workflow.
> docs: refactor component contribution checklist

- src/DateInput/index.js
- stories/DateInput/index.js
- stories/__snapshots__/storyshots.test.js.snap
Includes the DateSelector strings in the strings prop
and pass this strings down to DateSelector
> Fix translation strings prop

- src/Table/TableAggregationRow.js
- src/Table/TableEmptyItem.js
- src/Table/TableExpandedItem.js
- src/Table/TableExpandedRow.js
- src/Table/TableHead.js
- src/Table/TableRow.js
- src/Table/index.js
> table: refactor style

- src/TabBar/TabBar.js
- src/TabBar/TabItem.js
- stories/TabBar/index.js
- stories/__snapshots__/storyshots.test.js.snap
Organizaçao de código e alteração do `name` no `TabItem` para funcionar a navegação via teclado.
> tab-bar: refactor style

- src/Button/index.js
- stories/Button/index.js
- stories/__snapshots__/storyshots.test.js.snap
That prop will make icon to be inserted in left or right side of button text.
> Button: add iconPosition prop

- src/Switch/Switch.test.js
- src/Switch/index.js
- src/Switch/index.md
- stories/__snapshots__/storyshots.test.js.snap
add name prop so the input can be accessed
note that I also updated the alphabetical order of the props as @rsmelo told you were starting doing it
> switch: add name prop

- src/Dropdown/Dropdown.js
- stories/Dropdown/default.js
- stories/Dropdown/form.js
- stories/__snapshots__/storyshots.test.js.snap
> dropdown: fix render when a value is provided

- src/Table/README.md
- src/Table/TableEmptyRow.js
- src/Table/examples/TableState.js
- src/Table/index.js
- src/Table/tests/Table.static.test.js
- src/Table/tests/common.js
- stories/Table/TableState.js
- stories/Table/index.js
- stories/__snapshots__/storyshots.test.js.snap
Add prop `emptyMessage` to the `table` component.
When the `table` receive no rows this new property allows the `table` to render a empty row with the received message.
> Add table empty row 

- src/Input/Input.js
- stories/Input/form.js
- stories/__snapshots__/storyshots.test.js.snap
the `inputRef` prop helps users triggering a `focus` event on a specific
input
the 'keyPress` prop is used to trigger a function when the user press a specific keyboard key.
i.e. pressing Return to send a form
> input: add new handle props

- src/Input/Input.js
- stories/Input/default.js
This PR adds property passthrough to inner input. Properties like `maxLength`, `minLength`, `placeholder`, etc will be passed through the inner input.
> input: add props passthrough to inner input

- src/Modal/Modal.js
- src/Modal/ModalTitle.js
- stories/Modal/index.js
- stories/__snapshots__/storyshots.test.js.snap
Refactor modal structure manly the title and remove some unused structures.
Uses https://github.com/pagarme/former-kit-skin-pagarme/pull/70
> Modal refactoring

- src/LinearProgress/LinearProgress.test.js
- src/LinearProgress/example/style.css
- src/LinearProgress/index.js
- src/LinearProgress/index.md
- stories/Progress/index.js
- stories/Progress/style.css
- stories/__snapshots__/storyshots.test.js.snap
Adicionado novas classes para o novo estilo e atributos para acessibilidade.
> progress: refactor component

- src/Modal/README.md
- src/Modal/examples/ModalWithState.js
Refactor modal styleguide adding more examples
> Refactor modal styleguide

- src/Steps/Step.js
- src/Steps/index.js
- src/Steps/index.md
- stories/Steps/index.js
- stories/__snapshots__/storyshots.test.js.snap
> Refactor steps: add new status and remove background color

- stories/Card/CardExamples.js
- stories/Card/index.js
- stories/__snapshots__/storyshots.test.js.snap
Stories refatoradas para mostrar os títulos com `<strong></strong>` dentro.
> card: refactor stories

- package.json
- yarn.lock
Bump `former-kit-skin-pagarme` to version `0.5.1` and `former-kit` version to `0.5.1`
> Release version 0.5.1

- src/Modal/ModalSection.js
- src/Modal/README.md
- src/Modal/examples/ModalWithState.js
- src/Modal/index.js
- stories/Modal/index.js
- stories/__snapshots__/storyshots.test.js.snap
https://github.com/pagarme/former-kit-skin-pagarme/pull/87
> modal: add section component

- src/Input/Input.js
- src/Input/Input.test.js
- stories/Input/default.js
- stories/Input/form.js
> input: fix to pass event in onBlur and onFocus

- src/Avatar/index.js
- stories/Avatar/index.js
- stories/Header/HeaderContentExample.js
- stories/__snapshots__/storyshots.test.js.snap
Refactor component to use `Image` to handle with `onError` img.
> avatar: refactor render when src is invalid

- src/Input/Input.js
- src/Input/Input.test.js
Add renderer prop and tests to input component
> Add input renderer 

- package.json
Bump former-kit-skin-pagarme and version to 0.5.2
> Release version 0.5.2

- src/Layout/examples/SidebarState.js
- src/SegmentedSwitch/SegmentedSwitch.test.js
- src/SegmentedSwitch/index.js
- src/SegmentedSwitch/index.md
- src/Sidebar/README.md
- stories/SegmentedSwitch/index.js
- stories/Sidebar/SidebarState.js
- stories/__snapshots__/storyshots.test.js.snap
- Resolves: #108
- Allow icons in title
> segmented-switch: refactor interface to allow titles

- src/Avatar/index.md
- src/Grid/README.md
- src/Header/README.md
- src/Layout/examples/HeaderContentExample.js
- yarn.lock
This PR fix missing props on docs from `Header` and `Avatar` components
> docs: fix missing props and header component

- src/Pagination/index.js
- stories/Pagination/index.js
- stories/__snapshots__/storyshots.test.js.snap
- Add tiny size
https://github.com/pagarme/former-kit-skin-pagarme/pull/90
> pagination: add size prop

- src/Dropdown/Dropdown.js
- src/Dropdown/Dropdown.md
- src/Dropdown/example/DropdownState.js
- stories/Dropdown/default.js
- stories/__snapshots__/storyshots.test.js.snap
- Add tiny size
https://github.com/pagarme/former-kit-skin-pagarme/pull/91
> dropdown: add size prop

- config/styleguide.config.js
- src/Card/CardSectionDoubleLineTitle.js
- src/Card/CardSectionDoubleLineTitle.test.js
- src/Card/README.md
- stories/Card/CardSectionDoubleLineTitle.js
- stories/__snapshots__/storyshots.test.js.snap
Add actions options and refactor click area in card section double line title component
vinculado https://github.com/pagarme/former-kit-skin-pagarme/pull/88
> card-section-double-line-title: refactor component

- config/styleguide.config.js
This PR add a comma on styleguide settings.
> docs: fix styleguide settings

- .circleci/config.yml
This PR adds an steps to build styleguidist on circle ci.
> ci: add styleguide build

- src/Spacing/index.js
- stories/__snapshots__/storyshots.test.js.snap
- Add main class to the component
> spacing: add spacing class

- package.json
> release: bump version to 0.6.0

- config/styleguide.config.js
- src/Calendar/Calendar.test.js
- src/Calendar/examples/Calendar.js
- src/Calendar/index.js
- src/Calendar/index.md
- src/Calendar/normalizeDates.js
- src/index.js
- stories/Calendar/index.js
- stories/__snapshots__/storyshots.test.js.snap
- stories/index.js
Add calendar component, tests and examples.
In future will use the `DateSelector` will use `Calendar` component as child.
This component need the styles of the following PR:
https://github.com/pagarme/former-kit-skin-pagarme/pull/98
> Add calendar component

- src/Popover/Popover.js
- src/Popover/PopoverContent.js
- src/Popover/README.md
- src/Popover/index.js
- stories/Popover/Menu.js
- stories/Popover/PopoverControl.js
- stories/Popover/index.js
- stories/Popover/style.css
- stories/__snapshots__/storyshots.test.js.snap
This PR refactor the Popover component to handle with `visible`
prop from another event or component.
resolve #155
> popover: refactor to handle visible

- package.json
- yarn.lock
Update version to 0.7.0 from `former-kit` and `former-kit-skin-pagarme`
> Release v0.7.0

- src/Sidebar/SidebarContent.js
- src/Sidebar/SidebarHeader.js
- src/Sidebar/SidebarLink.js
- src/Sidebar/SidebarLinks.js
- stories/Sidebar/SidebarState.js
- stories/__snapshots__/storyshots.test.js.snap
- Add `Tooltip`
- Sort props
- Resolves https://github.com/pagarme/pilot/issues/741
- It links with https://github.com/pagarme/former-kit-skin-pagarme/pull/101
> sidebar: refactor link

- package.json
- yarn.lock
> release: bump version to 0.8.0

- src/SegmentedSwitch/index.js
- stories/SegmentedSwitch/index.js
- stories/__snapshots__/storyshots.test.js.snap
Add disabled prop to disable the component and change it style
> Segmented-switch add disabled option

- src/Card/CardSectionDoubleLineTitle.js
- stories/Card/CardSectionDoubleLineTitle.js
- stories/Card/index.js
- stories/__snapshots__/storyshots.test.js.snap
this PR fix `CardSectionDoubleLineTitle` subtitle render when subtitle is a node
> card-section-double-line: fix subtitle render

- package.json
- yarn.lock
> release: bump version to 0.8.1

- config/webpack.config.storybook.js
- package.json
- yarn.lock
- Update SVGR version
- Add title only as prop
- Bump emblematic-icons version
- Resolves https://github.com/pagarme/pilot/issues/808
> chore: update SVGR version

- config/styleguide.config.js
- src/BulletSteps/BulletStep.js
- src/BulletSteps/BulletSteps.test.js
- src/BulletSteps/index.js
- src/BulletSteps/index.md
- src/index.js
- stories/BulletSteps/index.js
- stories/__snapshots__/storyshots.test.js.snap
- stories/index.js
Add a new component, `bullet-step` (skin at https://github.com/pagarme/former-kit-skin-pagarme/pull/122)
closes https://github.com/pagarme/pilot/issues/861
> bullet-step: add component

- src/Input/Input.js
- src/Input/Input.test.js
- src/Input/example/InputState.js
- stories/Input/default.js
- stories/Input/form.js
- stories/__snapshots__/storyshots.test.js.snap
Refactor `Input` component to use the Dark base.
`Zeplin`: http://zpl.io/VqOdBA7
> input: add base dark

- src/Button/index.js
- stories/__snapshots__/storyshots.test.js.snap
This PR add ripple effect to handle with click feedback on `Button` component, depends on pagarme/former-kit-skin-pagarme#135
> button: add ripple effect

- src/Input/Input.js
- src/Input/Input.md
- src/Input/example/InputState.js
- stories/Input/default.js
- stories/__snapshots__/storyshots.test.js.snap
This PR add the `size` prop to `Input` component.
depends from pagarme/former-kit-skin-pagarme#141
**How test:**
- in `former-kit-skin-pagarme` checkout to `add/input-prop-size`
- run `yarn build`
- in `former-kit` checkout to this branch (`add/input-prop-size`)
- run `yarn storybook`
> input: add prop size

- package.json
- yarn.lock
This pull requests:
- bump version from 0.10.0 to 0.11.0
- bump former-kit-skin-pagarme dependency to 0.11.0
> update version to 0.11.0

- package.json
- yarn.lock
This PR updates the `former-kit-skin-pagarme` and releases new components and refactors.
The necessity of new component, refactor/fixes of the date inputs and improvements and components like `Sidebar`.
> Update version to 1.1.0

- config/styleguide.config.js
The current settings on styleguide don't configure the correct outpur dir.
> Fix styleguide settings

- package.json
> chore: update version to 1.2.0

- src/DateInput/index.js
- stories/DateInput/index.js
- stories/__snapshots__/storyshots.test.js.snap
This PR fixes the dates prop receive usage on component lifecycle
> DateInput - Fix dates lifecycle

- package.json
bumps version to 1.21
resolves #242
> update version to 1.2.1

- package.json
This PR bump to a minor version. `v1.3.0`
> chore: bump version to v1.3.0

- package.json
- yarn.lock
this release includes:
- button: add a loading state #255
- date-input: add moment peer dependency #254
- bumps `former-kit-skin-pagarme` to `1.2.0`
resolves #260
> release v1.4.0

- package.json
- yarn.lock
This PR updates the library version and `former-kit-skin-pagarme` version for the next release.
> Update version and dependencies

- stories/Card/CardSectionDoubleLineTitle.js
- stories/Typography/index.js
- stories/__snapshots__/storyshots.test.js.snap
This PR aims to fix small problems caused by the `font-family` change and the Card examples.
https://github.com/pagarme/former-kit-skin-pagarme/pull/194
https://github.com/pagarme/former-kit-skin-pagarme/issues/185
> Update font family and examples

- stories/Alert/index.js
- stories/Popover/Menu.js
- stories/__snapshots__/storyshots.test.js.snap
This branch solves minor problems related to the `font-family` change from Assistant to Rubik.
Depends on https://github.com/pagarme/former-kit-skin-pagarme/pull/194 and a new `former-kit-skin-pagarme` version
1 - Clone the `former-kit-skin-pagarme` project
```
git clone  git@github.com:pagarme/former-kit-skin-pagarme.git
```
2 - Get the remotes updates
```
cd former-kit-skin-pagarme
git fetch --all
```
3 - Move to the branch `update/font-family
```
git checkout update/font-family
```
4 - Create a Yarn link
```
yarn link
```
This command should return a message like the following one:
5 - Clone this project and install its dependencies
```
git clone  git@github.com:pagarme/former-kit.git
```
6 - Get the remotes updates
```
cd former-kit
git fetch --all
```
7 - Move to this branch
```
git …
```
> Update font family

- package.json
- yarn.lock
This release includes:
- Dateinput - Updates focus usability #307
- update  former-kit-skin-pagarme to 1.5.3
- update package version to 1.7.3
- Dateinput - Updates focus usability #307
resolves #308
> Release 1.7.3

- src/Input/Input.js
- stories/Input/default.js
- stories/Input/form.js
- stories/__snapshots__/storyshots.test.js.snap
Today our inputs don't have the type `tel` but have the type `phone` which isn't correct.
Correction example in the `form` inputs stories:
> Fix input type phone

- package.json
- src/SegmentedSwitch/SegmentedSwitch.js
This release includes:
- [segmented-switch: add classname prop](https://github.com/pagarme/former-kit/pull/320)
Resolves https://github.com/pagarme/tecnologia-vendas/issues/774
> Release v1.8.1

- package.json
This release adds:
- Export SecondaryFormDropdown #331
> release 1.9.1

- package.json
- src/Modal/Modal.js
- stories/Dropdown/default.js
- stories/Modal/ModalWithSmallSize.js
- stories/Modal/index.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
Este PR realiza as seguintes alterações:
- Adiciona o tamanho de modal pequeno
- Atualiza o estilo do bullet steps
- Atualiza o estilo padrão do dropdown
> modal: add small size

- package.json
- src/Button/Button.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
Seta o primeiro caracter do botão para ser maiusculo.
> button: update set first letter uppercase

- package.json
- yarn.lock
- Realiza o bump dos pacotes former-kit e emblematic-icons.
> CRED-99 Realiza o bump dos pacotes

- package.json
- src/Card/CardTitle.js
- src/TabBar/TabBar.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
**Contexto**
- Adiciona a opção de alinhar o Tab.
- Adiciona a opção de configurar o tamanho da fonte do cardTitle
> Ajustes no CardTitle e Tab

- package.json
- src/Sidebar/SidebarLink.js
- stories/Sidebar/SidebarState.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
Adicionar logica da borda no submenu 
Essa atividade depende desse PR: https://github.com/pagarme/former-kit-skin-pagarme/pull/300
- Rodar yarn
- Rodar o storybook e validar
> [EXP-1100] adicionar submenu de recorrência na sidebar

- package.json
- src/Button/Button.js
- src/Dropdown/Dropdown.js
- src/Sidebar/SidebarLink.js
- stories/__snapshots__/storyshots.test.js.snap
Este PR adiciona a propriedade data-testid em alguns componentes que estão sendo utilizados na Pilot, com isso conseguimos ter seletores especificos para os testes de transactions.
[issue](https://mundipagg.atlassian.net/browse/QA-1865?atlOrigin=eyJpIjoiNzM2MWVlMTc3YWU0NGJmZDhkNjk0NjgyODUwYzdiYjAiLCJwIjoiaiJ9)
> [QA-1865] Add data-testid

- package.json
- src/Checkbox/Checkbox.js
- src/DateInput/index.js
- src/DateSelector/Aside.js
- src/DateSelector/index.js
- src/Grid/Row.js
- src/Input/Input.js
- src/Legend/index.js
- stories/__snapshots__/storyshots.test.js.snap
Este PR adiciona a propriedade data-testid em alguns componentes que estão sendo utilizados na Pilot, com isso conseguimos ter seletores especificos para os testes de paymentLink.
[issue](https://mundipagg.atlassian.net/browse/QA-1868?atlOrigin=eyJpIjoiMjI1MmFjMjM1YzdkNGRlMmI5YjcyMjQ2ZjVmYzUyY2QiLCJwIjoiaiJ9)
> [QA-1868] Add data-testid

- package.json
> fix: change version

- README.md
- package.json
- src/Sidebar/SidebarLink.js
- src/Sidebar/SidebarLink.test.js
- stories/Sidebar/SidebarState.js
- stories/Sidebar/style.css
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
Adicionar validacao da chamada do onclick caso tiver sublink  e collapse for dinamico
https://www.figma.com/file/BdIMtgzXmliEz2ACBnTUsU/Proposta-de-Menu-Unificado?node-id=540%3A23977
Para funcionar corretamente vc precisa utilizar o former kit skin pagarme na mesma branch e linkar
- Caso o PR do formerkit for aprovado alterar a versao do mesmo aqui no formerkit antes de subir
- Necessario [desse](https://github.com/pagarme/former-kit-skin-pagarme/pull/310) PR no former kit skin pagarme 
- Acessar o componente e validar se abre apenas 1 menu
- Se o estilo segue como o proposto
> [EXP-1336]Adicionar validacao da chamada do onclick caso tiver sublink 

- package.json
- yarn.lock
Atualizacao former-kit-skin-pagarme
> Atualizacao former-kit-skin-pagarme

- package.json
- yarn.lock
Upadte former kit sking pagarme
> Upadte former kit sking pagarme

- .github/workflows/build_test_and_lint.yml
Este PR:
* Converte o CI para GitHub Actions
[issue](https://mundipagg.atlassian.net/browse/QA-2093?atlOrigin=eyJpIjoiNTcxOTNhNjY3MzVlNDcyNWFlNzEzOGUwZWIzZDg3OWEiLCJwIjoiaiJ9)
[insert screenshot here]
Não se aplica
[insert screenshot here]
Não se aplica
**New scripts**:
- `script` : script details
**New dependencies**:
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
Não se aplica
> QA 2093 - Include pipeline with GitHub Actions

- package.json
- src/DateSelector/Aside.js
- src/DateSelector/index.js
Ajustes do former kit para a demanda de Filtros.
> Release v2.17.0
