.circleci/config.yml
scripts/fetch-skin.sh

This solves the issue of visual diffs being out of date or requiring
a bump in skin-pagarme because of repository split.
It solves the issue by using the pull-request branch name to fetch
a branch of former-kit-skin-pagarme with the same name and `yarn link`
the packages.

When available, use skin-pagarme on same branch name for visual diffs

---

src/SegmentedSwitch/index.js
stories/__snapshots__/storyshots.test.js.snap

Alterei o `name` do input radio para `instanceId` pois os inputs estavam com names diferentes, prejudicando a navegação via teclado.

segmented-switch: refactor style

---

scripts/fetch-skin.sh

Currently we have a script which fetches the former-kit-skin-pagarme
repository with the same branch name as the pull request branch for
former-kit.
This allows us to do visual validation on Percy using the same skin
branch as the pull request.
When there's no branch available with the same name, the script just
bails out, effectively making former-kit use the skin version defined
in package.json, which gives us a bad experience for visual validations,
making changes have lots of regressions, until we bump skin on
dependencies.
This commit makes the script fallback to skin's master branch when no
branch with same name is found.

chore: fix skin fetch to use master branch

---

config/styleguide.config.js

Currently the styleguidist config has an reference to `SidebarSection` this cause an error when try to compile, this remove the reference from config.

chore: remove sidebar-section from styleguide

---

package.json
yarn.lock

Update `former-kit-skin-pagarme` to 0.5.2 to 0.6.0

chore: update former-kit-skin-pagarme version

---

src/Calendar/index.js
src/CalendarInput/index.js
src/DateInput/dateHelpers.js

Fix the calendar input behavior when the input receives an empty value and add `closeOnSelect` prop with default `true` for single date selection.
Closes #163

Fix calendar input

---

src/Tooltip/index.js
stories/Tooltip/index.js
stories/Tooltip/style.css
stories/__snapshots__/storyshots.test.js.snap

This PR adds `onHover` prop as a callback function to handle with hover events. With this, we can control the visibility of the `Tooltip` from outside of the component.

tooltip: refactor component

---

config/styleguide.config.js

This PR fix the `Popover` render error in docs:

docs: fix popover render error

---

src/Tooltip/index.js

This PR add a validation before calling `onMouseEnter` and `onMouseLeave` functions.

Tooltip: fix mouse functions missing in props

---

src/Input/Input.js

Despite that the [attribute `value` at `<input>` element is optional at HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), on `<Input>` at FormerKit this attribute is required.
This is a not expected behaviour and unnecessary. Because of this, some forms, such as [Pilot Login page](https://github.com/pagarme/pilot/blob/master/packages/pilot/src/containers/Account/Login/index.js#L21-L24), needs to set a blank value to each input. If it not set this empty value, React raises an error:
>Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: …

input: fix default prop "value"

---

stories/Section.js
stories/style.css

I've added a Dark base to the `Section` component of the Storybook to make it easier to see the components that will be with the Dark base.
I also added the variables of the Former-Kit-Skin and put 16px instead of 15px on the margins and paddings of the `style.css` file.

section: add dark base

---

src/Alert/index.js
stories/Alert/index.js
stories/__snapshots__/storyshots.test.js.snap

Refactor `Alert` component to use the Dark base.
`Zeplin`: http://zpl.io/aRMjP80

alert: add base dark

---

src/Alert/index.js

There were missing strings in the `Alert` theme provider.
https://zpl.io/aRMjP80

alert: fix base theme strings

---

src/Modal/Modal.js
stories/Modal/index.js

In order for the before-close property to be viewed, I had to modify the component to receive a property called "closeTimeoutMS". To know more about this rule, [click here](http://reactcommunity.org/react-modal/styles/classes.html).
This PR is related to https://github.com/pagarme/former-kit-skin-pagarme/pull/148 and https://github.com/pagarme/pilot/pull/1014.
- Go to `add/modal-transition` branch in all repositories
```
git checkout add/modal-transition
```
- Create a link to former-kit-skin e former-kit repositories
```
yarn link
```
- Link former-kit-skin-pagarme
```
yarn link former-kit
```
- Link former-kit-skin-pagarme inside Pilot
```
yarn link former-kit
yarn link former-kit-skin
```
- Run normally storybook at former-kit/Pilot
```
yarn storybook
```

Modal: add "closeTimeoutMS" prop

---

src/Popover/Popover.js
stories/Popover/index.js
stories/__snapshots__/storyshots.test.js.snap

This PR add the `closeWhenClickOutside` to component to handle with cases when it is not allowed close the popover.

popover: add prop to handle with click outside

---

package.json
yarn.lock

This PR updates some dependencies:
- updates  react-dev-utils@5.0.0 to 5.0.3
- updates  react-dom@16.2.0 to 16.2.1
- updates  webpack-dev-server@2.11.1 to 2.11.3
- updates react-styleguidist@6.2.1 to 6.2.7
**New dev dependencies**:
- updates  react-dev-utils@5.0.0 to 5.0.3
- updates  react-dom@16.2.0 to 16.2.1
- updates  webpack-dev-server@2.11.1 to 2.11.3
- updates react-styleguidist@6.2.1 to 6.2.7

chore: update depencies patch version

---

src/DateSelector/index.js
stories/DateSelector/index.js
stories/__snapshots__/storyshots.test.js.snap

This PR add the `selectedPreset` prop to DateSelector.
just run the storybook

date-selector: add selectedPreset prop

---

src/Dropdown/Dropdown.js
stories/__snapshots__/storyshots.test.js.snap

O component de `select` recebia uma prop chamada `defaultValue` que era encarregada de passar o valor padrão para o component e apresentar se houvesse esse valor, porém não existia essa prop dado isso, mudamos para `value` como é dito na documentação do react (https://reactjs.org/docs/forms.html#the-select-tag) fazendo isso, se o `value` refletir algum dos valores de `options` já virá com esse valor selecionado e adicionando a tag `selected` a aquela option.

dropdown: fix prop value

---

src/Layout/examples/SidebarState.js
src/Sidebar/README.md
src/Sidebar/Sidebar.js
src/Sidebar/index.js
stories/Sidebar/SidebarState.js
stories/__snapshots__/storyshots.test.js.snap

This is part of Sidebar's MicroInteration https://github.com/pagarme/pilot/issues/854 .

sidebar: add expanded className and removes SidebarContent component

---

src/Tag/index.js

This PR changes the `children` prop validation to accept other types besides strings. Now we can pass a `node`(string, array, element or function) as children.
This will solve the Tag warnings when elements are received as children.
The following picture shows the error, it occurs in this case because we mix React elements and text inside the `Tag` component.

Refactor Tag component props

---

package.json
src/Calendar/index.js
src/CalendarInput/index.js
src/DateInput/index.js
src/DateSelector/index.js
src/index.js
src/validations/index.js
src/validations/momentProp.js
stories/__snapshots__/storyshots.test.js.snap
yarn.lock

Ao utilizar o DateInput com a prop `selectedPreset`, o preset é selecionado mas a sua data não é inserida no input de texto. Este PR soluciona este problema.
**Solves:** https://github.com/pagarme/former-kit/issues/235

DateInput - Adiciona no input a data do preset pré-selecionado

---

src/Table/index.js

The `TableLoaderRow` component handle with `colSpan` in a wrong way ignoring the `maxColumns` and `expandable` props.
This PR fix this by considering these props.
Related #249

table-loader-row: update colspan handlers

---

package.json
yarn.lock

This PR remove `ˆ` from `react-input-mask` dependency.
Resolve #245

chore: update range version from package

---

package.json
yarn.lock

This PR fixes MM/DD/YYYY to DD/MM/YYYY.
- Go to `fix/anticipation-moment-js` branch
- Generate a link to `former-kit` repository
- Go to Pilot and run `yarn link former-kit`
- Run Pilot locally and see with the problem persists. If don't persist, that's it! :tada: 
```
"moment": "^2.24.0"
```

date-input: add moment peer dependency and add mask prop

---

package.json
src/Tooltip/index.js
src/Truncate/index.js
stories/Truncate/style.css
yarn.lock

This PR solve the React dependencies issue and fix the width calculation in the Truncate component
In the `master` branch setting the padding in the examples, we can get this error:
In this branch, the same example should look like this:
To test this in Pilot project you must create an npm package and change the `former-kit` reference to this new package.
To create and link a new npm package you could use the following steps:
1 - Clone this project
2 - Go to the cloned folder and Install all dependencies and build the project
```
cd former-kit
yarn 
yarn build
```
3 - Create an npm pack
```
npm pack
```
4 - In the project which is using former-kit changes its reference to the absolute path for the created pack
```
```
5 - Install all the new dependencies and run your project

Refactor dependencies and truncate

---

src/Tooltip/index.js

This PR fixes adds classname prop to Tooltip component. 
Depends on https://github.com/pagarme/pilot/pull/1244 and https://github.com/pagarme/former-kit-skin-pagarme/pull/177

Tooltip: Add classname prop

---

package.json
yarn.lock

This releases includes:
- Tooltip: Add classname prop #266
- bump dependency `former-kit-skin-pagarme` from `1.3.0` to `1.3.2`
- Resolves #268

Release 1.5.2

---

jest.config.js
src/Modal/Modal.js
src/Modal/Modal.md
src/Modal/examples/ModalWithState.js
stories/Modal/ModalWithHugeSize.js
stories/Modal/ModalWithState.js
stories/Modal/index.js
stories/__snapshots__/storyshots.test.js.snap

This PR adds a new props to the Modal component called `size`. This new props will control the width of the Modal component and have two parameters: `default` and `huge`
- `git clone` in this repo
- `yarn` to install dependencies
- `yarn link` to link `former-kit-skin-pagarme` if it is not updated
- `yarn storybook` to run local

Add a new props to Modal component: size

---

src/DateInput/index.js
stories/DateInput/index.js
stories/DateInput/style.css
stories/__snapshots__/storyshots.test.js.snap

When presets were received by props in the `DateInput` component the `componentDidMount` wasn't changing the component state.
1 - Clone this project and install its dependencies
```
git clone  git@github.com:pagarme/former-kit.git
```
2 - Get the remotes updates
```
cd former-kit
git fetch --all
```
3 - Move to this branch
```
git checkout fix/date-input-presets
```
4 - install the dependencies
```
yarn
```
5 - Run the Storybook
```
yarn storybook
```
6 - look for the `with sidebar and selected preset` story, it must be changing the `DateInput`correctly when the preset is changed in the `DropDown`, like in the following example:

Fix DateInput presets

---

src/Truncate/index.js

This PR removes the `React.memo` a function which was doing a wrong cache for the component props.
In a few cases, in Pilot, the truncate wasn't working correctly.

Remove react memo from Truncate

---

src/DateInput/index.js

This Pull Request solves a problem with the optional usage of the `selectedPreset` prop, which should not cause a problem if not informed.

DateInput - Refactor selectedPreset usage

---

package.json
yarn.lock

- add property size to Modal component
- fix DateInput presets usage
- remove react memo from Truncate component
- update dependecy `former-kit-skin-pagarme` to `1.3.3`
- Add a new props to Modal component: size #270
- Fix DateInput presets #274
- Fix DateInput presets #275
- Remove react memo from Truncate #276
- DateInput - Refactor selectedPreset usage #278
resolves #281

Release 1.5.3

---

src/SegmentedSwitch/SegmentedSwitch.js
stories/SpacedSegmentedSwitch/index.js
stories/__snapshots__/storyshots.test.js.snap

We need to implement a `relevance` prop for `SpacedSegmentedSwitch` which will be used as a period selection on Pilot's home.
1. Link with `former-kit-skin-pagarme/add/low-relevance-segmentedswitch`
2. Run storybook

SegmentedSwitch - Add props for relevance and spacing

---

src/Table/TableHead.js
src/Table/examples/TableState.js
src/Table/index.js
src/Table/tests/Table.static.test.js
src/Table/tests/common.js
stories/Table/TableState.js
stories/Table/TableStateWidthControl.js
stories/Table/index.js
stories/__snapshots__/storyshots.test.js.snap

This PR solves two problems that was happening in recipients table:
- `status` column was too large for a few small information
- overlap in `id` informations when the screen size changes
This PR is part of this Card: https://github.com/pagarme/former-kit/issues/272 . It is possible to see examples of the problem there.
Screenshots here:  https://github.com/pagarme/former-kit/issues/272
- `git clone` in this repo
- `yarn` to install dependencies
- `yarn link "former-kit-skin-pagarme` to link
- `yarn storybook`
do not forget to change the second column title to _"Id do Recebedor"_  for the condition to work

Table PR: add condition to control sizes in recipients table

---

src/DateInput/index.js

Dates were not changing when using `dates` prop, also, typing the date manually caused the selection mode to change unexpectedly. So this PR reverts some of our latests changes to fix that. 
1. Link this branch with pilot's `master`
2. Use DateInput from Transactions Search page

DateInput - Fix preset and mode selection

---

src/DateSelector/index.js
stories/DateSelector/index.js
stories/__snapshots__/storyshots.test.js.snap

In order to accomplish our design necessities, we need to be able to control the DateSelector's `placement` prop. This pull request adds it to the component.

DateSelector - add placement prop

---

src/DateInput/index.js

If we filter for a period of days in a row on the Extract page, an error is caused in `dateHelpers`, displaying the modal failure of the application. This PRs fixes `momentToText` validation.

Date Input: Fix momentToText validation

---

src/Popover/Popover.js
src/Tooltip/index.js

Improve `prop-types` restricting the amount of values accepted by `placement` on `Tooltip` and `Popover` components.

placement: improve prop-types

---

src/Sidebar/SidebarLink.js

Sometimes makes sense to add a menu on sidebar that needs to start opened, to be more noticeable by the user and easy to use.
So this PR add a new prop to be able to customise it: `childrenBeginOpen`

sidebar-link: add prop beginExpanded

---

src/Truncate/index.js

In some cases when property text is update the text rendered by the component is no updated.
This pull request change the validation inside the useEffect to always update the `currentText` state when the property text changes
- checkout branch `fix/truncate-update`
- create a link `yarn link`
- install dependencies `yarn start`
- build the package `yarn build`
- go to the pilot repo directory
- checkout branch `release/v0.21.0`
- link with `former-kit` `yarn link former-kit`
- start pilot `yarn start`
- navigate to the transactions list page
- filter the transacions by a issue that is not the in the first row
- the column `Nome` needs to update the value displayed
- Inconsistência no nome do cliente na listagem de transações https://github.com/pagarme/pilot/issues/1445

truncate fix text update

---

src/Sidebar/SidebarContent.js
src/Sidebar/index.js

The component `SidebarContent` is documented and is necessary on some situations - but it isn't exported.
This PR fixes it exporting it in order to be able to use on others projects.

sidebar-content: fix its export

---

src/Legend/index.js
stories/__snapshots__/storyshots.test.js.snap

This PR adds `textColor` prop to Legend component.
- Generate an link with `yarn link` in this repository
- Link to Pilot's project in `cd packages/pilot` with `yarn link former-kit`
- Run and see if `Autorizado` legend in Transações is with `#000000` text color.

legend: add textColor prop

---

package.json
yarn.lock

- update  former-kit-skin-pagarme to 1.5.2
- update package version to 1.7.2
- legend: add textColor prop #305
- checkout branch bump/former-kit-skin
- run `yarn` to install new dependencias
- run `yarn build` to check if the project is building ok
- run `yarn storybook` and check if everything is running ok

release 1.7.2

---

src/DateInput/index.js
src/DateSelector/index.js

We need to make our DateInput more user friendly, and our input focus handling is an important step towards that. This Pull Request intends to not change it when selecting presets from DateInput's sidebar.
- Click on a date preset and the input selection should be kept on the start date

Dateinput - Updates focus usability

---

src/Legend/index.js
stories/Legend/index.js
stories/__snapshots__/storyshots.test.js.snap

Legend component needs to be changed in order to receive a new property. 
css content: https://github.com/pagarme/former-kit-skin-pagarme/pull/218
- clone the repo `https://github.com/pagarme/former-kit-skin-pagarme`
- run `git checkout add/legend-class`, `yarn` and  `yarn build`
- Generate the link of former-kit-skin-pagarme: `yarn link`.
- Link the former-kit-skin-pagarme with the former-kit: clone the former-kit repository and run `git checkout add/legend-prop`, `yarn` and `yarn link former-kit-skin-pagarme`
- Run `yarn storybook`
- Open `Legend` 
- Check `With capitalize letters` and `With uppercase letters`.

add format property to Legend component

---

package.json
yarn.lock

This release includes:
- Legend: add new property `textFormat`
- Input: fix type property to accepts `tel` instead of `phone` to be compatible with public DOM interface
- update  former-kit-skin-pagarme to 1.5.4
- update package version to 1.7.4
- add format property to Legend component #313
- Fix input type phone #311
resolves #314

Release 1.7.4

---

package.json
yarn.lock

This release includes:
- ProgressBar: alternative style
- bump `former-kit-skin-pagarme` to `1.6.0`
- bump `handlebars` from `4.1.2` to `4.5.3`
resolves #318

Release v1.8.0

---

src/SegmentedSwitch/SegmentedSwitch.js

This PR adds `className` prop in `<SegmentedSwitch />`. With this, we can add other classes in the component.
Knowing that this PR is helping with https://github.com/pagarme/linkapp/pull/245, you can test there with these steps:
- Go to `add/future-balance-container` in linkapp repository
- Generate a link from this branch in former-kit repository with `yarn link`
- Go to linkapp and `yarn link former-kit`
- Add a class in `<SpacedSegmentedSwitch />` component in  `src/containers/OperationDays/index.js`
- See if it works! :tada:

segmented-switch: add classname prop

---

src/Modal/Modal.js
stories/Modal/ModalWithMobileSize.js
stories/Modal/index.js
stories/__snapshots__/storyshots.test.js.snap

Precisamos do modal compativel com tamanho mobile para uso no linkApp.
- no `former-kit-skin` entre na branch `add/modal-mobile-size`
- rode `yarn link`
- no `former-kit` entre na branch `add/modal-mobile-size` 
- rode `yarn link "former-kit-skin-pagarme"`
- rode `yarn storybook`
- cheque a historia do Modal com tamanho mobile

Adiciona tamanho mobile no componente Modal

---

package.json
yarn.lock

This release adds:
- Modal: mobile size #325
- bump former-kit-skin-pagarme to `1.7.0`
resolves #326

release 1.8.2

---

src/Dropdown/Dropdown.js
src/Dropdown/secondary-form/index.js
stories/Dropdown/index.js
stories/Dropdown/secondaryForm.js
stories/__snapshots__/storyshots.test.js.snap

This PR add the new dropdown variant that is required for the Onboarding history (https://github.com/pagarme/credenciamento/issues/437 and https://github.com/pagarme/pilot/issues/1579).
css content: https://github.com/pagarme/former-kit-skin-pagarme/pull/233
Telas: https://www.figma.com/file/kVlmDxHiI7FQcOARicddD2/Onboarding?node-id=0%3A1

dropdown: add SecondaryDropdown

---

package.json
yarn.lock

This release adds:
- SecondaryButton #323
- SecondaryDropdown #329
- Bump acorn related dependencies #328
- bump former-kit-skin-pagarme to `1.8.0`

release 1.9.0

---

package.json
src/Button/Button.js
src/Card/CardSectionDoubleLineTitle.js
src/Popover/Popover.js
stories/Card/CardSectionDoubleLineTitle.js
stories/__snapshots__/storyshots.test.js.snap

O componente CardSectionDoubleLineTitle atualmente só é clicável na seta ao final do card. Muitos clientes acabam clicando no título ou em outros lugares para abrir o componente, poderíamos então deixar toda a seção de cima clicável para melhorar a usabilidade.

fix: card clickacle area

---

package.json
src/Header/HeaderMenu.js
src/Popover/Popover.js
stories/Popover/index.js
stories/__snapshots__/storyshots.test.js.snap
yarn.lock

Este pr adiciona uma nova prop para o component de `popover`
- Baixar o `former-kit-skin-pagarme` que possue a branch com o mesmo nome dessa 
- Executar o `yarn`
- Executar o `yarn build` no `former-kit-skin-pagarme`
- Executar o `yarn link` no `former-kit-skin-pagarme`
- Baixar a branch `chore/adjust-popover`
- Executar o `yarn`
- executar o comando `yarn link former-kit-skin-pagarme`
- Executar o comando `yarn install --force`
- Executar o `storybook` e checar o popover `withoutArrow`

chore: add new arrow props to popover component

---

package.json
src/CalendarInput/index.js
src/DateInput/examples/DateInputState.js
src/Pagination/index.js
src/Popover/Popover.js
src/SegmentedSwitch/SegmentedSwitch.md
src/Tooltip/index.js
stories/Colors/index.js
stories/SegmentedSwitch/index.js
stories/SpacedSegmentedSwitch/index.js
yarn.lock

Atualiza para React 17, removendo as funções de ciclo de vida do componente que estavam depreciadas . A única função que não foi removida, foi `componentWillReceiveProps` que foi renomeada para a versão UNSAFE. Será necessário refatorar alguns componentes para remover essa função, e isso será feito em uma issue separada.

[EXP-659] Bump React to 17.0.2 

---

package.json
src/Popover/Popover.js
src/Popover/ReactClickOutside.js
src/Popover/ReactClickOutside.test.js
yarn.lock

O componente Popover utiliza o o pacote react-click-outside, para saber quando o usuário clica fora da área do popover. O problema é que esse pacote não funciona corretamente dentro de um shadow dom (O popover abre e fecha imediatamente).
Isso acontece porque quando esse pacote é usado com shadow-dom, o `event.target` do evento de click, retorna o shadow-dom e não o elemento correto dentro do shadow-dom. Por isso, foi necessário fazer um componente internamente dentro do former-kit, baseado no react-click-outside, modificando o comportamento para que funcione também com shadow-dom.
1. Rodar testes do former-kit e garantir que os testes (antigos e os do ReactClickOutside) estão passando.
1. Usar o npm link no former-kit e linkar na pilot
2. Testar os lugares que usam Popover na aplicação e …

[EXP-693] Refactor/react click outside

---

package.json
src/Button/Button.js
src/Button/Button.md
stories/Button/default.js
stories/__snapshots__/storyshots.test.js.snap

Estratégia para componentizar botão sem padding
- [Estratégia para componentizar botão sem padding](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&projectKey=EXP&modal=detail&selectedIssue=EXP-879)
**Preview com former-kit-skin-pagarme:**

[EXP-879] Componentizar botão sem padding

---

package.json
src/Input/Input.js
src/Input/Input.test.js
src/Snackbar/Snackbar.test.js
stories/Input/default.js
stories/Input/form.js
stories/__snapshots__/storyshots.test.js.snap

Atualmente a máscara utilizada no componente `<Input />` possuí uma opção interna de desativar o carácter de preenchimento de máscara, porém não está sendo exportado em um Prop. 
Esse PR adiciona essa prop no componente
- Rode o storybook e verifique o storie `Masked input without Masked Char` está executando um Input sem máscara

[MDX-1483] Adiciona prop charMask no InputMask

---

package.json
src/Checkbox/Checkbox.js
src/Input/Input.js
stories/__snapshots__/storyshots.test.js.snap
yarn.lock

- Atualiza todas as dependência que estava sendo acusada de vunerabilidade pelo `dependabots`
- Remove o atributo `maskchar` da tag input, que estava sendo inserida sempre na tag, assim corrigindo um erro que emitia no console
- Verifique o componente `Input` do storybook e veja se o erro no console desapareceu (como mostra a print a baixo)
- Verifique se os builds estão passando

Release - Atualiza depencias do dependabots e correção no maskChar

---

.circleci/config.yml

The circleCI team notified us:
`I wanted to reach out because I noticed that there are still legacy convenience images being used in your account. These images are being deprecated in two rounds with the first round starting on Dec 31st. They will not be deleted, but they will no longer be supported. Below is a list of the projects currently using those images.`
This PR updates the Node image.

QA 1705 - refactor: update image

---

package.json
src/Sidebar/SidebarLink.js
stories/Sidebar/SidebarState.js
stories/__snapshots__/storyshots.test.js.snap

Esse PR implementa uma alteração no SidebarLink, adicionando uma div para separar o icone da esquerda e o texto do link, da seta da direita. Para que com um `justify-content: space-between` o link mantenha a seta separada no seu canto direito. Além disso, inclui duas novas propriedades no `SidebarLink`, sendo elas: `hasSeparator` que indicará se o item deverá possuir uma separação dos itens acima, e `iconRight`,  que irá adicionar um icone a direita do menu. 
- [EXPRECEBE-492] 
[EXPRECEBE-492]: https://mundipagg.atlassian.net/browse/EXPRECEBE-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EXPRECEBE-492] Alterar espaçamento do ícone do menu no former-kit-skin
